### ISSUE TITLE
What tools you use for draw a diagram in your code as comment?

### ISSUE THREAD

**Issue by wuliJerry** [rhysd/riscv32-cpu-chisel#1]
Excuse me, with all my respect, I was wondering what tool you use to generate diagrams of CPU in the comments of your codes. BTW I know this might have nothing to do with your project itself, but I really want to know. Thanks for your help in advance.

**Comment by rhysd** [comment]
Vim.

**Comment by Rogerskelamen** [comment]
Sorry to bother, but I want to know what exactly the name of vim plugin you use to draw the diagram. Thanks if you could reply.
